---
kind: pipeline
name: argos-release
type: docker

steps:
  - name: check license
    image: rabobanknl/argos-build:latest
    commands:
    - mvn license:check
 
  - name: build integrated snapshot image
    image: plugins/docker
    settings:
      context: docker
      dockerfile: docker/Dockerfile
      repo: argosnotary/argos-snapshot
      tags: ${DRONE_BRANCH/\//_}${DRONE_TAG}
      build_args:
        - ARGOS_VERSION=${DRONE_BRANCH/\//_}${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - push
        
  - name: build and release integrated image
    image: plugins/docker
    settings:
      context: docker
      dockerfile: docker/Dockerfile
      repo: argosnotary/argos
      auto_tag: true
      build_args:
        - ARGOS_VERSION=${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - tag     
      
trigger:
  event:
    - push
    - tag

