---
kind: pipeline
name: argos-release
type: docker

steps:
  - name: check license
    image: argosnotary/argos-build:3.6.3
    commands:
    - mvn license:check
 
  - name: build integrated snapshot image
    image: plugins/docker
    settings:
      context: docker
      dockerfile: docker/Dockerfile
      repo: argosnotary/argos-snapshot
      tags: ${DRONE_TAG:-${DRONE_BRANCH//\//_}}
      build_args:
        - ARGOS_VERSION=0.0.1-RC6
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - push
        
  - name: build helm snapshot chart
    image: argosnotary/argos-build:3.6.3
    commands:
    - cd helm/charts
    - helm chart save argos/ "argosnotary/argos-chart-snapshot:${DRONE_TAG:-${DRONE_BRANCH//\//_}}"
    - helm chart push "argosnotary/argos-chart-snapshot:${DRONE_TAG:-${DRONE_BRANCH//\//_}}"
    when:
      event:
        - push
        
  - name: build and release integrated image
    image: plugins/docker
    settings:
      context: docker
      dockerfile: docker/Dockerfile
      repo: argosnotary/argos
      auto_tag: true
      build_args:
        - ARGOS_VERSION=${DRONE_TAG}
      username:
        from_secret: docker_login_user
      password:
        from_secret: docker_login_token
    when:
      event:
        - tag
        
  - name: build helm and release chart
    image: argosnotary/argos-build:3.6.3
    commands:
    - cd helm/charts
    - helm chart save argos/ "argosnotary/argos-chart:${DRONE_TAG}"
    - helm chart save argos/ argosnotary/argos-chart:latest
    - helm chart push "argosnotary/argos-chart:${DRONE_TAG}"
    - helm chart save argos/ argosnotary/argos-chart:latest
    when:
      event:
        - tag    
      
trigger:
  event:
    - push
    - tag

